variable "environment" {}
variable "api_sg_id" {}
variable "public_subnets_id" {}
variable "ssh_key_name" {}
variable "instance_type" {}
variable "device_name" {}
variable "volume_size" {}
variable "volume_type" {}
variable "database" {}
variable "dbuser" {}
variable "db" {}
variable "iam_ec2_s3_profile" {}
variable "owners" {}
variable "ami_prefix" {}
